---

env:
  browser: true
  es6: true
  node: true
  jest: true
extends: 
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
